server:
  port: 8888
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.apitestplatform.model.entity
  type-enums-package: com.example.apitestplatform.enums
  global-config:
    db-config:
      id-type: id_worker
      logic-delete-value: Y
      logic-not-delete-value: N
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://39.96.20.187:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: Cathy051229*
          driver-class-name: com.mysql.cj.jdbc.Driver

swagger:
  enable: true
  application-name: api-test-platform
  application-version: 1.0
  application-description: 测试平台后台服务